import type { Metadata } from "next";
import "./globals.css";
// import Link from 'next/link';
import { SessionProvider } from "next-auth/react";
import Keep from "@/components/keep/keep";
import Auth from "@/components/keep/auth";

export const metadata: Metadata = {
  title: "KEEP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <div id="app">
          <header className="border-b border-neutral-200 dark:border-neutral-800">
            <div className="section">
              <div className="flex justify-between items-center">
                <div className="flex gap-2 items-center">
                  <Keep />
                </div>
                <div className="flex gap-2 items-center">
                  <SessionProvider>
                    <Auth />
                  </SessionProvider>
                </div>
              </div>
            </div>
          </header>
          <main>
            {children}
          </main>
          <footer className="border-t border-neutral-200 dark:border-neutral-800">
            <div className="section text-center">
              &copy; {(new Date().getFullYear())}. KEEP. All rights reserved.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
